# Generated by Django 5.0 on 2024-02-28 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('describtion', models.TextField(max_length=300)),
                ('complete', models.BooleanField(default=False)),
                ('task_assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_due_date', models.DateField(blank=True, null=True)),
                ('category', models.ManyToManyField(to='category.taskcategory')),
            ],
        ),
    ]
